<template>
  <Layout :title="$page.project.title">


<div class="job-explain">
  <g-image
        class="job-bg"
        :src="$page.project.thumbnail"
        :alt="$page.project.title"
      />
  <div class="job-logos">
    <svg viewBox="0 -13 512 512" xmlns="http://www.w3.org/2000/svg" style="background-color:#2e2882">
        <g fill="#feb0a5">
         <path d="M256 92.5l127.7 91.6L512 92 383.7 0 256 91.5 128.3 0 0 92l128.3 92zm0 0M256 275.9l-127.7-91.5L0 276.4l128.3 92L256 277l127.7 91.5 128.3-92-128.3-92zm0 0"></path>
         <path d="M127.7 394.1l128.4 92 128.3-92-128.3-92zm0 0"></path>
        </g>
        <path d="M512 92L383.7 0 256 91.5v1l127.7 91.6zm0 0M512 276.4l-128.3-92L256 275.9v1l127.7 91.5zm0 0M256 486.1l128.4-92-128.3-92zm0 0" fill="#feb0a5"></path>
    </svg>
  </div>
  <div class="job-explain-content">
    

       <ProjectMeta
        :title="$page.project.title"
        :categories="$page.project.categories"
        :year="$page.project.year"
       />
       
      
       
       <div class="overview-text">
        <div class="overview-text-header">Overview</div>
        <div class="overview-text-subheader">We believe that design (and you) will be critical to the company's success. You will work with our founders and our early customers to help define and build our product functionality, while maintaining the quality bar that customers have come to expect from modern SaaS applications. You have a strong background in product design with a quantitavely anf qualitatively analytical mindset. You will also have the opportunity to craft our overall product and visual identity and should be comfortable to flex into working.</div>
       </div>
       <div class="overview-text">
        <div class="overview-text-header">Job Description</div>
        <div class="overview-text-item">3+ years working as a product designer.</div>
        <div class="overview-text-item">A portfolio that highlights your approach to problem solving, as well as you skills in UI.</div>
        <div class="overview-text-item">Experience conducting research and building out smooth flows.</div>
        <div class="overview-text-item">Excellent communication skills with a well-defined design process.</div>
        <div class="overview-text-item">Familiarity with design tools like Sketch and Figma</div>
        <div class="overview-text-item">Up-level our overall design and bring consistency to end-user facing properties</div>
       </div>
      </div>
     </div>



  </Layout>
</template>

<page-query>
query Project ($path: String!) {
  project: project(path: $path) {
    title
    thumbnail
    year
    categories
    content
  }
}
</page-query>

<script>
import ProjectMeta from "@/components/ProjectMeta";

export default {
  components: {
    ProjectMeta
  },
  mounted() {
    // Instead of checking for firstChild nodes that is text elements,
    // check and see if the p tags only contains img elements and that noscript
    // generated by Gridsome.
    const contentElements = document.querySelectorAll("p");
    contentElements.forEach(
      element =>
        element.firstChild.nodeName === "#text" &&
        element.classList.add("content-text")
    );
  }
};
</script>

<style lang="css">
.project-post {
  padding: 0 2rem;
  margin-bottom: 8rem;
}
img {
  width: 100% !important;
  margin-bottom: 2rem;
  border-radius: 10px;
}
p {
  margin: 0;
}
.content-text {
  padding: 4rem 0 6rem 0;
  font-size: 2rem;
  font-weight: 400;
  margin-left: 0;
  max-width: 780px;
  line-height: 1.5;
  @media (min-width: 920px) {
    margin-left: 40%;
  }
}























.job-card-title{font-weight:600;margin-top:16px;font-size:14px;}
.job-explain{background-color:var(--header-bg-color);border-radius:0 0 8px 8px;}
.job-bg{border-radius:8px 8px 0 0;-o-object-fit:cover;object-fit:cover;width:100%;height:180px;transition:0.3s;position:relative;}
.job-logos {
    margin-top: -50px;
    position: relative;
    margin-bottom: -36px;
    padding: 0 20px;
}
.job-logos svg{width:66px;padding:12px;background-color:#fff;border-radius:10px;border:4px solid var(--header-bg-color);}
.job-title-wrapper{display:flex;align-items:center;}
.job-title-wrapper .job-card-title{font-size:20px;margin-top:0;font-weight:600;}
.job-action{display:flex;align-items:center;margin-left:auto;}
.job-action svg{width:32px;border:1px solid var(--border-color);color:var(--subtitle-color);border-radius:8px;padding:6px;}
.job-action svg + svg{margin-left:12px;}
.job-explain-content{padding:50px 25px 30px;}
.job-subtitle-wrapper{display:flex;align-items:center;margin-top:20px;}
.job-subtitle-wrapper .posted{margin-left:auto;}
.job-subtitle-wrapper .company-name{color:var(--active-color);font-weight:600;font-size:14px;}
.job-subtitle-wrapper .comp-location,.job-subtitle-wrapper .posted{color:var(--subtitle-color);font-size:12px;font-weight:500;}
.job-subtitle-wrapper .comp-location{position:relative;margin-left:10px;}
.job-subtitle-wrapper .comp-location:before{content:"";width:3px;height:3px;border-radius:50%;background-color:var(--placeholder-color);top:49%;left:-8px;position:absolute;}
.job-subtitle-wrapper .app-number{color:var(--body-color);position:relative;margin-left:12px;}
.job-subtitle-wrapper .app-number:before{content:"";width:3px;height:3px;border-radius:50%;background-color:var(--placeholder-color);top:50%;left:-7px;position:absolute;}
.explain-title{color:var(--subtitle-color);font-size:12px;line-height:40px;white-space:nowrap;}
.explain-subtitle{font-size:13px;font-weight:500;margin-top:-2px;white-space:nowrap;}
.explain-contents{height:66px;}
.explain-contents + .explain-contents{border-left:1px solid var(--border-color);padding-left:16px;}
.overview-text{margin-top:30px;}
.overview-text-header{font-weight:600;margin-bottom:25px;}
.overview-text-subheader{font-size:13px;line-height:2em;}
.overview-text-item {
  font-size:13px;
  position:relative;
  display:flex;
  align-items: center;
}
.overview-text-item + .overview-text-item{margin-top:20px;}
.overview-text-item:before {
  content:"";
  border:2px solid #3fb288;
  border-radius:50%;
  height:8px;
  width:8px;
  margin-right:8px;
  flex-shrink:0;
}
@media screen and (max-width: 990px){
.explain-contents,.explain-bar{height:auto;}
.explain-bar{flex-wrap:wrap;padding-bottom:14px;}
.explain-contents{width:50%;}
.explain-contents + .explain-contents{padding:0;border:0;}
.explain-contents:nth-child(2) ~ .explain-contents{margin-top:16px;border-top:1px solid var(--border-color);}
.job-subtitle-wrapper{flex-direction:column;align-items:flex-start;}
.job-subtitle-wrapper .posted{margin-left:0;margin-top:6px;}
}
@media screen and (max-width: 760px){
.job-explain{margin-left:0;}
}
@media screen and (max-width: 380px){
.explain-contents{width:100%;margin:0;}
.explain-contents:nth-child(2) ~ .explain-contents{margin:0;border:0;}
}</style>